import type {
  AdvancedControlState,
  CodingAppTypeOption,
  CodingFeatureOption,
  CodingGeneratorDraft,
  CodingToolOption,
  OutputVariantOption,
  ProductRequirementFieldOption,
  ProductRequirementSection,
  ProductRequirementState,
  PromptStrengthOption,
  TechStackCategory,
  TechStackOption,
} from './types.ts';

export const CODING_GENERATOR_STORAGE_KEY = 'ai-coding-generator:draft';

export const CODING_TOOL_OPTIONS: CodingToolOption[] = [
  {
    id: 'claude-code',
    label: 'Claude Code',
    shortLabel: 'Claude Code',
    helper: 'Best when you want repo-aware implementation guidance with disciplined planning and verification.',
    bestFor: 'Deep codebase changes, refactors, and architecture-sensitive work.',
    priority: 1,
  },
  {
    id: 'github-copilot',
    label: 'GitHub Copilot',
    shortLabel: 'Copilot',
    helper: 'Good for branch-based implementation, repo workflows, and developer-in-the-loop execution.',
    bestFor: 'Feature work inside active repositories with strong IDE support.',
    priority: 2,
  },
  {
    id: 'cursor',
    label: 'Cursor',
    shortLabel: 'Cursor',
    helper: 'Strong fit for interactive coding sessions that combine prompt context with code edits.',
    bestFor: 'Fast iteration across multi-file frontend or full-stack work.',
    priority: 3,
  },
  {
    id: 'claude',
    label: 'Claude',
    shortLabel: 'Claude',
    helper: 'Useful when the handoff will be pasted into a chat-oriented assistant instead of an IDE agent.',
    bestFor: 'Planning, review, and prompt-first implementation guidance.',
    priority: 4,
  },
  {
    id: 'bolt',
    label: 'Bolt.new',
    shortLabel: 'Bolt',
    helper: 'Works well for greenfield prototypes and rapid app scaffolding with explicit guardrails.',
    bestFor: 'Small-to-medium app builds where speed matters.',
    priority: 5,
  },
  {
    id: 'replit-agent',
    label: 'Replit Agent',
    shortLabel: 'Replit',
    helper: 'Useful for browser-based coding sessions that need clear implementation phases and QA steps.',
    bestFor: 'Hosted prototypes and smaller full-stack builds.',
    priority: 6,
  },
  {
    id: 'v0',
    label: 'v0',
    shortLabel: 'v0',
    helper: 'Best for UI-first generation where component structure, states, and responsive design need precision.',
    bestFor: 'Design-system aligned UI and frontend scaffolding.',
    priority: 7,
  },
];

export const APP_TYPE_OPTIONS: CodingAppTypeOption[] = [
  {
    id: 'full-stack-web',
    label: 'Full-stack web app',
    helper: 'Frontend plus backend, data model, auth, and deployment concerns.',
    deliverableHint: 'Expect UI, API, persistence, testing, and deployment notes.',
  },
  {
    id: 'frontend-web',
    label: 'Frontend web app',
    helper: 'UI-heavy work with component architecture, responsive behavior, and client-side state.',
    deliverableHint: 'Expect component boundaries, state flow, and responsive QA instructions.',
  },
  {
    id: 'api-backend',
    label: 'API or backend service',
    helper: 'Server endpoints, business logic, integrations, jobs, and persistence.',
    deliverableHint: 'Expect contracts, validation, persistence, and observability guidance.',
  },
  {
    id: 'mobile-app',
    label: 'Mobile app',
    helper: 'Native or cross-platform application flows, device constraints, and release checks.',
    deliverableHint: 'Expect screen flows, offline states, and device QA coverage.',
  },
  {
    id: 'browser-extension',
    label: 'Browser extension',
    helper: 'Popup, content scripts, background workers, and permissions-aware UX.',
    deliverableHint: 'Expect manifest, permission boundaries, and browser-specific verification.',
  },
  {
    id: 'cli-tool',
    label: 'CLI or automation tool',
    helper: 'Command-driven workflows, scripting, config handling, and terminal UX.',
    deliverableHint: 'Expect command design, flags, validation, and output examples.',
  },
  {
    id: 'ai-agent',
    label: 'AI workflow or agent system',
    helper: 'Agent orchestration, tool use, prompt design, and safety controls.',
    deliverableHint: 'Expect workflow boundaries, evals, tool contracts, and guardrails.',
  },
  {
    id: 'library-sdk',
    label: 'Library or SDK',
    helper: 'Reusable package APIs, docs, tests, and version-safe changes.',
    deliverableHint: 'Expect public API design, examples, and backward-compatibility notes.',
  },
];

export const FEATURE_OPTIONS: CodingFeatureOption[] = [
  { id: 'auth', label: 'Authentication', helper: 'Sign in, roles, sessions, and protected access.', category: 'Core' },
  { id: 'dashboard', label: 'Dashboard', helper: 'Overview surfaces, KPIs, widgets, and summaries.', category: 'Core' },
  { id: 'billing', label: 'Billing', helper: 'Plans, subscriptions, invoicing, and usage controls.', category: 'Business' },
  { id: 'cms', label: 'CMS or content management', helper: 'Editable content, forms, and publishing workflows.', category: 'Business' },
  { id: 'search', label: 'Search and filtering', helper: 'Discovery, faceting, filters, and result states.', category: 'Core' },
  { id: 'notifications', label: 'Notifications', helper: 'Email, in-app, push, and alerting flows.', category: 'Communication' },
  { id: 'analytics', label: 'Analytics', helper: 'Tracking, reporting, and operational insights.', category: 'Communication' },
  { id: 'admin', label: 'Admin tools', helper: 'Back-office views, moderation, and internal controls.', category: 'Operations' },
  { id: 'api-integration', label: 'Third-party integrations', helper: 'External APIs, webhooks, and sync flows.', category: 'Operations' },
  { id: 'realtime', label: 'Realtime updates', helper: 'Live presence, sockets, streaming, and collaborative state.', category: 'Core' },
  { id: 'ai-workflows', label: 'AI workflows', helper: 'Prompt chains, model calls, tools, and agent behaviors.', category: 'Operations' },
  { id: 'offline-sync', label: 'Offline sync', helper: 'Queued actions, local persistence, and reconnection logic.', category: 'Operations' },
];

export const TECH_STACK_CATEGORIES: TechStackCategory[] = [
  { id: 'frontend', label: 'Frontend', helper: 'UI frameworks, styling, and component systems.' },
  { id: 'backend', label: 'Backend', helper: 'Server frameworks and runtime choices.' },
  { id: 'data', label: 'Data', helper: 'Persistence, ORM, cache, and hosted data tools.' },
  { id: 'testing', label: 'Testing', helper: 'Unit, integration, and end-to-end tooling.' },
  { id: 'delivery', label: 'Delivery', helper: 'Deploy, CI, hosting, and infrastructure preferences.' },
];

export const TECH_STACK_OPTIONS: TechStackOption[] = [
  { id: 'react', label: 'React', helper: 'Component-driven frontend with a large ecosystem.', categoryId: 'frontend' },
  { id: 'nextjs', label: 'Next.js', helper: 'React framework for app routing, SSR, and full-stack delivery.', categoryId: 'frontend' },
  { id: 'vue', label: 'Vue', helper: 'Component-driven frontend with ergonomic templates.', categoryId: 'frontend' },
  { id: 'typescript', label: 'TypeScript', helper: 'Typed implementation and safer refactors.', categoryId: 'frontend' },
  { id: 'tailwind', label: 'Tailwind CSS', helper: 'Utility-first styling aligned with this app.', categoryId: 'frontend' },
  { id: 'shadcn', label: 'shadcn/ui', helper: 'Composable UI primitives and design-system reuse.', categoryId: 'frontend' },
  { id: 'node', label: 'Node.js', helper: 'JavaScript or TypeScript server runtime.', categoryId: 'backend' },
  { id: 'express', label: 'Express', helper: 'Minimal HTTP API routing and middleware.', categoryId: 'backend' },
  { id: 'python', label: 'Python', helper: 'Good fit for data, API, and automation services.', categoryId: 'backend' },
  { id: 'fastapi', label: 'FastAPI', helper: 'Typed Python APIs with schema-first ergonomics.', categoryId: 'backend' },
  { id: 'postgres', label: 'PostgreSQL', helper: 'Relational data model with strong production support.', categoryId: 'data' },
  { id: 'prisma', label: 'Prisma', helper: 'Typed ORM and schema-driven migrations.', categoryId: 'data' },
  { id: 'supabase', label: 'Supabase', helper: 'Hosted database, auth, and storage toolkit.', categoryId: 'data' },
  { id: 'redis', label: 'Redis', helper: 'Cache, queues, ephemeral data, and rate limiting.', categoryId: 'data' },
  { id: 'vitest', label: 'Vitest', helper: 'Fast unit and component testing in Vite projects.', categoryId: 'testing' },
  { id: 'jest', label: 'Jest', helper: 'General-purpose test runner with mature mocking support.', categoryId: 'testing' },
  { id: 'playwright', label: 'Playwright', helper: 'Cross-browser end-to-end and regression testing.', categoryId: 'testing' },
  { id: 'cypress', label: 'Cypress', helper: 'Interactive end-to-end browser testing.', categoryId: 'testing' },
  { id: 'docker', label: 'Docker', helper: 'Containerized local dev and deployment parity.', categoryId: 'delivery' },
  { id: 'vercel', label: 'Vercel', helper: 'Fast deployment for frontend or Next.js apps.', categoryId: 'delivery' },
  { id: 'render', label: 'Render', helper: 'Managed hosting for APIs, workers, and full-stack apps.', categoryId: 'delivery' },
  { id: 'github-actions', label: 'GitHub Actions', helper: 'CI workflows, automation, and deploy checks.', categoryId: 'delivery' },
];

export const PROMPT_STRENGTH_OPTIONS: PromptStrengthOption[] = [
  {
    id: 'standard',
    label: 'Standard',
    helper: 'Lean, useful, and fast. Good for scoped tasks where the repo context is already understood.',
    difference: 'Gives clear implementation instructions without over-specifying every checkpoint.',
  },
  {
    id: 'strong',
    label: 'Strong',
    helper: 'Adds repo audit, phased planning, architecture checks, and stronger verification expectations.',
    difference: 'Best default when you want fewer wrong turns and more explicit execution sequencing.',
  },
  {
    id: 'god',
    label: 'God Mode',
    helper: 'Exhaustive, opinionated, and highly defensive. Pushes the agent to minimize risk and justify changes.',
    difference: 'Adds stricter guardrails, rollback thinking, and zero-assumption execution behavior.',
  },
];

export const OUTPUT_VARIANT_OPTIONS: OutputVariantOption[] = [
  {
    id: 'full-prompt',
    label: 'Full Prompt',
    helper: 'Complete repo-aware handoff with context, constraints, workflow, and deliverables.',
  },
  {
    id: 'condensed-prompt',
    label: 'Condensed Prompt',
    helper: 'Shorter version for agents that work best with tighter prompts.',
  },
  {
    id: 'execution-checklist',
    label: 'Execution Checklist',
    helper: 'Operational task list for agents or human reviewers to follow step by step.',
  },
  {
    id: 'implementation-brief',
    label: 'Implementation Brief',
    helper: 'Compact product + engineering brief that frames the build before coding starts.',
  },
];

export const PRODUCT_REQUIREMENT_SECTIONS: ProductRequirementSection[] = [
  {
    id: 'foundation',
    label: 'Foundation',
    helper: 'Clarify core product and platform expectations before the agent starts coding.',
  },
  {
    id: 'experience',
    label: 'Experience',
    helper: 'Describe the visual, responsive, and user-facing expectations that should shape implementation.',
  },
  {
    id: 'quality',
    label: 'Quality and trust',
    helper: 'Capture non-functional requirements that prevent weak or release-risky output.',
  },
  {
    id: 'operations',
    label: 'Operations and guardrails',
    helper: 'Specify admin workflows, automations, analytics, and hard constraints the agent must honor.',
  },
];

export const PRODUCT_REQUIREMENT_FIELDS: ProductRequirementFieldOption[] = [
  {
    key: 'auth',
    sectionId: 'foundation',
    label: 'Auth requirements',
    helper: 'Sign-in methods, session behavior, and protected access requirements.',
    placeholder: 'Email/password, magic link, SSO, guest mode, MFA, invite-only access...',
    checklistHint: 'Confirm authentication flows, session handling, and protected routes or endpoints.',
    multiline: true,
  },
  {
    key: 'roles',
    sectionId: 'foundation',
    label: 'Roles and permissions',
    helper: 'Who can do what, and where role-based restrictions matter.',
    placeholder: 'Admin can manage users, managers can approve requests, viewers are read-only...',
    checklistHint: 'Map role and permission rules to UI, API, and data-access behavior.',
    multiline: true,
  },
  {
    key: 'dataStorage',
    sectionId: 'foundation',
    label: 'Database and storage',
    helper: 'Primary persistence, object storage, cache, or queue expectations.',
    placeholder: 'PostgreSQL for core data, S3 for uploads, Redis for queueing...',
    checklistHint: 'Align schemas, persistence, and storage choices with the requested data model.',
    multiline: true,
  },
  {
    key: 'integrations',
    sectionId: 'foundation',
    label: 'APIs and integrations',
    helper: 'External systems, APIs, webhooks, or internal services that must connect cleanly.',
    placeholder: 'Stripe billing, Slack alerts, CRM sync, internal REST service...',
    checklistHint: 'Define integration boundaries, failure handling, and data contracts.',
    multiline: true,
  },
  {
    key: 'deployment',
    sectionId: 'foundation',
    label: 'Deployment target',
    helper: 'Hosting platform, environments, and release assumptions.',
    placeholder: 'Vercel frontend, Render API, Dockerized worker, GitHub Actions CI...',
    checklistHint: 'Match configuration, environment assumptions, and deploy steps to the target platform.',
    multiline: true,
  },
  {
    key: 'designStyle',
    sectionId: 'experience',
    label: 'Design and visual style',
    helper: 'Describe how the UI should feel, especially if it must reuse an existing design system.',
    placeholder: 'Operational dashboard, polished enterprise UI, editorial landing page, calm consumer app...',
    checklistHint: 'Reflect the requested visual style while reusing established design-system patterns.',
    multiline: true,
  },
  {
    key: 'responsive',
    sectionId: 'experience',
    label: 'Responsive requirements',
    helper: 'Key breakpoints, device priorities, or form-factor constraints.',
    placeholder: 'Desktop first, tablet-friendly, mobile parity for key flows...',
    checklistHint: 'Validate the requested device and breakpoint behavior before considering the work done.',
    multiline: true,
  },
  {
    key: 'accessibility',
    sectionId: 'experience',
    label: 'Accessibility',
    helper: 'Keyboard, focus, semantics, contrast, or screen-reader expectations.',
    placeholder: 'WCAG AA, keyboard nav, visible focus, semantic forms, reduced motion...',
    checklistHint: 'Include accessibility requirements in both implementation and verification.',
    multiline: true,
  },
  {
    key: 'seo',
    sectionId: 'experience',
    label: 'SEO and metadata',
    helper: 'Metadata, schema, crawl, and indexability expectations when relevant.',
    placeholder: 'Route metadata, Open Graph, canonical tags, structured data, sitemap...',
    checklistHint: 'Account for metadata and crawlability requirements where the app has public surfaces.',
    multiline: true,
  },
  {
    key: 'localization',
    sectionId: 'experience',
    label: 'Localization and RTL',
    helper: 'Languages now, future localization, and right-to-left constraints.',
    placeholder: 'English now, plan for French and Arabic later, avoid hardcoded layout assumptions...',
    checklistHint: 'Avoid implementation choices that block future localization or RTL support.',
    multiline: true,
  },
  {
    key: 'testing',
    sectionId: 'quality',
    label: 'Testing requirements',
    helper: 'What level of automated or manual coverage is expected.',
    placeholder: 'Vitest unit tests, Playwright smoke coverage, regression checks, API contract tests...',
    checklistHint: 'Run or add the requested coverage level and report evidence.',
    multiline: true,
  },
  {
    key: 'performance',
    sectionId: 'quality',
    label: 'Performance requirements',
    helper: 'Latency, rendering, cache, or bundle expectations.',
    placeholder: 'Fast first render, cached dashboard queries, avoid expensive rerenders, lazy load heavy routes...',
    checklistHint: 'Protect the requested performance characteristics and avoid obvious regressions.',
    multiline: true,
  },
  {
    key: 'security',
    sectionId: 'quality',
    label: 'Security requirements',
    helper: 'Sensitive flows, validation, audit, or abuse-prevention expectations.',
    placeholder: 'Validate inputs, protect admin routes, audit sensitive actions, rate limit public endpoints...',
    checklistHint: 'Account for validation, authorization, and security-sensitive edge cases.',
    multiline: true,
  },
  {
    key: 'adminWorkflow',
    sectionId: 'operations',
    label: 'Admin workflow',
    helper: 'Back-office or internal operations flows that need first-class support.',
    placeholder: 'Admin approval queue, moderation panel, manual override, support tooling...',
    checklistHint: 'Treat admin and internal operations flows as explicit product requirements.',
    multiline: true,
  },
  {
    key: 'automation',
    sectionId: 'operations',
    label: 'Automation triggers',
    helper: 'Scheduled jobs, webhooks, reminders, or workflow triggers.',
    placeholder: 'Send reminders when overdue, trigger webhook on status change, schedule nightly sync...',
    checklistHint: 'Define automation triggers, timing, and failure behavior clearly.',
    multiline: true,
  },
  {
    key: 'analytics',
    sectionId: 'operations',
    label: 'Analytics and event tracking',
    helper: 'Events, reporting, and product measurement requirements.',
    placeholder: 'Track signup completion, dashboard usage, conversion events, audit admin actions...',
    checklistHint: 'Add event tracking and analytics instrumentation where requested.',
    multiline: true,
  },
  {
    key: 'mustNotDo',
    sectionId: 'operations',
    label: 'Must-not-do constraints',
    helper: 'Hard boundaries that prevent the agent from taking risky shortcuts.',
    placeholder: 'Do not rewrite auth, do not swap UI libraries, do not change schema, do not touch billing...',
    checklistHint: 'Explicitly avoid the prohibited changes while implementing the requested work.',
    multiline: true,
  },
];

export const DEFAULT_PRODUCT_REQUIREMENTS: ProductRequirementState = {
  auth: '',
  roles: '',
  dataStorage: '',
  integrations: '',
  deployment: '',
  testing: '',
  designStyle: '',
  responsive: '',
  accessibility: '',
  performance: '',
  security: '',
  seo: '',
  localization: '',
  adminWorkflow: '',
  automation: '',
  analytics: '',
  mustNotDo: '',
};

export const DEFAULT_ADVANCED_CONTROLS: AdvancedControlState = {
  repoAuditFirst: true,
  planBeforeCoding: true,
  architectureAwareness: true,
  preferExistingPatterns: true,
  minimalRewrites: true,
  phasedImplementation: true,
  requireTests: true,
  requireResponsiveQa: true,
  deployAfterVerification: true,
  includeAcceptanceCriteria: true,
  includeRollbackNotes: false,
};

export const DEFAULT_CODING_GENERATOR_DRAFT: CodingGeneratorDraft = {
  targetToolId: 'claude-code',
  websiteId: '',
  websiteName: '',
  websiteContext: '',
  projectName: '',
  projectSummary: '',
  targetUsers: '',
  currentState: '',
  repoContext: '',
  appTypeId: '',
  selectedFeatureIds: [],
  customFeatures: '',
  selectedTechStackIds: ['react', 'typescript', 'tailwind'],
  customStackNotes: '',
  advancedNotes: '',
  productRequirements: DEFAULT_PRODUCT_REQUIREMENTS,
  promptStrength: 'strong',
  outputMode: 'full-prompt',
  advanced: DEFAULT_ADVANCED_CONTROLS,
};
